[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=57ce4b14-71f0-4785-90e1-2bd2fb6ae591
Description=GunsUp自动购买攻击卡
Enable=0
AutoRun=1
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
'在1920*1080分辨率下，打开“补给站”→“卡片包”，然后运行本脚本，即可自动购买价格5000的10张进攻卡片。
MoveTo 872, 337
KeyPress "Space", 1
Delay 1000
KeyPress "Space", 1
Delay 1000
KeyPress "Space", 1
Delay 1000
KeyPress "Space", 1
Delay 1000

'==========以上是按键精灵录制的内容==========
